import { defineConfig } from 'wxt';

/**
 * WXT config for the X post composer extension.
 *
 * Security posture (see CLAUDE.md §6):
 *  - host_permissions restricted to x.com and twitter.com — no <all_urls>.
 *  - permissions include only what the extension actually uses.
 *  - The API key is read only by the background service worker via the
 *    storage layer; this config does not handle secrets.
 */
export default defineConfig({
  srcDir: '.',
  modules: ['@wxt-dev/module-react'],
  // Auto-imports add hidden behavior. This is a public, security-sensitive
  // extension where every import should be explicit and inspectable — see
  // CLAUDE.md §1 (ethos: honest, transparent, no magic).
  imports: false,
  manifest: {
    name: 'Margin',
    description:
      'In the margin of X — a scratch pad for composing X.com posts and replies in your own voice. Bring your own Anthropic API key.',
    // sidePanel.open() requires Chrome 116; everything else we use
    // (sidePanel API 114, oklch/color-mix CSS 111) is older. Without
    // this floor, older Chromes would install a broken extension.
    minimum_chrome_version: '116',
    // Generated by scripts/generate-icons.py from the brand-mark design
    // — committed PNGs, reproducible from the script.
    icons: {
      16: 'icon/16.png',
      32: 'icon/32.png',
      48: 'icon/48.png',
      128: 'icon/128.png',
    },
    permissions: ['storage', 'sidePanel', 'clipboardWrite', 'unlimitedStorage'],
    host_permissions: [
      'https://x.com/*',
      'https://www.x.com/*',
      'https://twitter.com/*',
      'https://www.twitter.com/*',
    ],
    action: {
      default_title: 'Open Margin',
      default_icon: {
        16: 'icon/16.png',
        32: 'icon/32.png',
        48: 'icon/48.png',
        128: 'icon/128.png',
      },
    },
    side_panel: {
      default_path: 'sidepanel.html',
    },
    commands: {
      'capture-reply-and-open': {
        // Chrome only allows Alt/Ctrl/Shift modifier combos for cross-OS
        // shortcuts; users can rebind at chrome://extensions/shortcuts.
        suggested_key: {
          default: 'Alt+Shift+R',
          mac: 'Alt+Shift+R',
        },
        description: 'Open Margin and start capturing reply context',
      },
    },
  },
});
